/* eslint-disable react/no-unescaped-entities */
/* eslint-disable max-lines */
/* eslint-disable @next/next/no-page-custom-font */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700;800&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className={styles.navBar}>
        <Image
          alt="logo"
          height="35"
          src="/assets/pngs/logo_with_text.png"
          width="112"
        />
        <button className={styles.navLaunchButton} type="button">
          <div className={styles.navLaunchButtonText}>Launch App</div>
        </button>
      </div>
      <div className={styles.warning}>
        <div>
          <b>UPDATE:</b>&nbsp;
          <a>
            The beta test has ended and we are officially soft launched. The
            capacity of Vodka and Water have been increased to 200k and 100k
            respectively.
          </a>
        </div>
        <button type="button">
          <Image
            alt="close"
            height="15"
            src="/assets/svgs/close.svg"
            width="15"
          />
        </button>
      </div>
      <div className={styles.container}>
        <main className={styles.main}>
          <div className={styles.mainLeft}>
            <div>
              <a className={styles.titleLeft}>SECURE</a>&nbsp;
              <a className={styles.titleRight}>FUND</a>
            </div>
            <div>
              <a className={styles.titleLeft}>SECURE</a>&nbsp;
              <a className={styles.titleRight}>RETURN</a>
            </div>
            <a className={styles.description}>
              Build up capital under Market Neutral approach
            </a>
            <button className={styles.launchButton} type="button">
              Launch App
            </button>
          </div>
          <div className={styles.mainRight}>
            <Image
              alt="Vaultka Logo"
              height="466"
              src="/assets/svgs/main_logo.svg"
              width="482"
            />
            <Image
              alt="Vaultka Logo"
              height="80"
              src="/assets/svgs/logo_line.svg"
              width="500"
            />
          </div>
        </main>
        <div className={styles.subContainer}>
          <a className={styles.title}>Growth & Traction</a>
          <div className={styles.secondChildContainer}>
            <div className={styles.secondChildSubContainer}>
              <a className={styles.valueLabel}>70k</a>
              <a className={styles.descriptionLabel}>Total Users</a>
            </div>
            <div className={styles.secondChildSubContainer}>
              <a className={styles.valueLabel}>100k</a>
              <a className={styles.descriptionLabel}>Total Value Lock</a>
            </div>
          </div>
        </div>
        <div className={styles.separatorLine} />
        <div className={styles.subContainer}>
          <a className={styles.title}>High-yield protected USDC Savings</a>
          <a className={styles.subTitle}>
            Build up your USDC wtih Vaultka’s Savings, empower various
            strategies for out-perform-market stablecoins yield
          </a>
          <div className={styles.thirdChildContainer}>
            <div className={styles.thirdChildSubContainer}>
              <a className={styles.thirdChildTitle}>Savings</a>
              <a className={styles.thirdChildDescription}>
                Save USDC into Vaultka savings vault, enable various automated
                strategies to generate out-performed-market stablecoins yield
              </a>
            </div>
            <div className={styles.thirdChildSubContainer}>
              <Image
                alt="Vaultka Logo"
                layout="fill"
                src="/assets/svgs/saving.svg"
              />
            </div>
          </div>
          <a className={styles.title}>Automated Strategies</a>
          <a className={styles.subTitle}>
            Automating complex strategies with Vaultka. Securing yield with risk
            management and auto-compounding
          </a>
          <div className={styles.forthChildContainer}>
            <div className={styles.forthChildSubContainer}>
              <div className={styles.forthChildSubContainerLeft}>
                <a className={styles.forthChildTitle}>Vodka Strategy - GMX </a>
                <div className={styles.separatorLine} />
                <a className={styles.forthChildSubTitle}>
                  GLP Delta Neutral Strategy
                </a>
                <a className={styles.forthChildDescription}>
                  GLP predominately composite of BTC, ETH and stablecoins. that
                  is acted as the counterpart of traders in GMX perpetual
                  trading platform. Vaultka strategy hedges the BTC and ETH
                  based on GLP composition, enabling delta-neutral position to
                  capture yield.
                </a>
                <button className={styles.forthChildButton} type="button">
                  Invest Now!
                </button>
              </div>
              <div className={styles.forthChildSubContainerRight}>
                <Image
                  alt="Vodka Strategy"
                  height="208"
                  src="/assets/svgs/vodka_strategy.svg"
                  width="245"
                />
                <a className={styles.forthChildSubContainerTitle}>
                  Vodka Strategy
                </a>
                <div className={styles.forthChildSubContainerMain}>
                  <div className={styles.forthChildSubContainerMainBox}>
                    <a className={styles.forthChildSubContainerMainBoxLabel}>
                      APY
                    </a>
                    <a className={styles.forthChildSubContainerMainBoxValue}>
                      15.21%
                    </a>
                  </div>
                  <div className={styles.forthChildSubContainerMainBox}>
                    <a className={styles.forthChildSubContainerMainBoxLabel}>
                      TVL
                    </a>
                    <a className={styles.forthChildSubContainerMainBoxValue}>
                      $273,414.3
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={styles.forthChildContainer}>
            <div className={styles.forthChildSubContainer}>
              <div className={styles.forthChildSubContainerLeft}>
                <a className={styles.forthChildTitle}>
                  Whiskey Strategy - Mycelium
                </a>
                <div className={styles.separatorLine} />
                <a className={styles.forthChildSubTitle}>
                  MLP Delta Neutral Strategy
                </a>
                <a className={styles.forthChildDescription}>
                  MLP predominately composite of BTC, ETH and stablecoins. that
                  is acted as the counterpart of traders in Mycelium Perpetual
                  Swap v2. Vaultka strategy hedges the BTC and ETH based on MLP
                  composition.
                </a>
                <a className={styles.forthChildComingLabel}>Coming Soon...</a>
              </div>
              <div className={styles.forthChildSubContainerRight}>
                <Image
                  alt="Vodka Strategy"
                  height="208"
                  src="/assets/svgs/whiskey_strategy.svg"
                  width="245"
                />
                <a className={styles.forthChildSubContainerTitle}>
                  Whiskey Strategy
                </a>
                <a className={styles.forthChildSubContainerSubTitle}>
                  Expected Launch Date: 20 March 2023
                </a>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.collaborationContainer}>
          <a className={styles.title}>Collaborations and Supports</a>
          <div className={styles.collaborationItemCollection}>
            <div className={styles.collaborationItemContainer}>
              <Image
                alt="Arbitrum"
                height="75"
                src="/assets/svgs/arbitrum.svg"
                width="65"
              />
              <div className={styles.collaborationItemLabels}>
                <a className={styles.collaborationItemName}>Arbitrum</a>
                <a className={styles.collaborationItemDescription}>
                  Performance scaling solutions for Ethereum
                </a>
              </div>
            </div>
            <div className={styles.collaborationItemContainer}>
              <Image
                alt="GMX"
                height="75"
                src="/assets/svgs/gmx.svg"
                width="65"
              />
              <div className={styles.collaborationItemLabels}>
                <a className={styles.collaborationItemName}>GMX</a>
                <a className={styles.collaborationItemDescription}>
                  Decentralized Perpetual Exchange
                </a>
              </div>
            </div>
            <div className={styles.collaborationItemContainer}>
              <Image
                alt="Mycelium"
                height="75"
                src="/assets/svgs/mycelium.svg"
                width="65"
              />
              <div className={styles.collaborationItemLabels}>
                <a className={styles.collaborationItemName}>Mycelium</a>
                <a className={styles.collaborationItemDescription}>
                  Connecting global digital markets
                </a>
              </div>
            </div>
            <div className={styles.collaborationItemContainer}>
              <Image
                alt="Factor DAO"
                height="75"
                src="/assets/svgs/factor.svg"
                width="65"
              />
              <div className={styles.collaborationItemLabels}>
                <a className={styles.collaborationItemName}>Factor DAO</a>
                <a className={styles.collaborationItemDescription}>
                  Modular Asset Management Infrastruture
                </a>
              </div>
            </div>
            <div className={styles.collaborationItemContainer}>
              <Image
                alt="Gelato"
                height="75"
                src="/assets/svgs/gelato.svg"
                width="65"
              />
              <div className={styles.collaborationItemLabels}>
                <a className={styles.collaborationItemName}>Gelato</a>
                <a className={styles.collaborationItemDescription}>
                  Web3 decentralized backend
                </a>
              </div>
            </div>
            <div className={styles.collaborationItemContainer}>
              <Image
                alt="Hats Finance"
                height="75"
                src="/assets/svgs/hats.svg"
                width="65"
              />
              <div className={styles.collaborationItemLabels}>
                <a className={styles.collaborationItemName}>Hats Finance</a>
                <a className={styles.collaborationItemDescription}>
                  Creating the future of security
                </a>
              </div>
            </div>
            <div className={styles.collaborationItemContainer}>
              <Image
                alt="ArbitrumNews DAO"
                height="75"
                src="/assets/svgs/arbitrumnews.svg"
                width="65"
              />
              <div className={styles.collaborationItemLabels}>
                <a className={styles.collaborationItemName}>ArbitrumNews DAO</a>
                <a className={styles.collaborationItemDescription}>
                  DAO on Arbitrum that supports projects
                </a>
              </div>
            </div>
            <div className={styles.collaborationItemContainer}>
              <Image
                alt="Arbitrum Space"
                height="75"
                src="/assets/svgs/arbitrumspace.svg"
                width="65"
              />
              <div className={styles.collaborationItemLabels}>
                <a className={styles.collaborationItemName}>Arbitrum Space</a>
                <a className={styles.collaborationItemDescription}>
                  Golden Opportunities & Daily Digest News
                </a>
              </div>
            </div>
            <div className={styles.collaborationItemContainer}>
              <Image
                alt="Fortitude"
                height="75"
                src="/assets/svgs/fortitude.svg"
                width="65"
              />
              <div className={styles.collaborationItemLabels}>
                <a className={styles.collaborationItemName}>Fortitude</a>
                <a className={styles.collaborationItemDescription}>
                  Auditing the Future of Internet
                </a>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.separatorThickLine} />
        <div className={styles.subContainer}>
          <a className={styles.title}>Frequently Asked Questions</a>
          <div className={styles.questionContainer}>
            <div>
              <div className={styles.questionSubContainer}>
                <a className={styles.questionLabel}>
                  What is the mission of Vaultka?
                </a>
                <button className={styles.questionCollapseButton} type="button">
                  -
                </button>
              </div>
              <a className={styles.answerLabel}>
                Vaultka is dedicated to offering the best vault strategy to the
                community, by providing the best risk-managed and delta-neutral
                strategies that empower users to earn out-performed-market
                stablecoins yield.
              </a>
              <div className={styles.questionSeparatorLine} />
            </div>
            <div>
              <div className={styles.questionSubContainer}>
                <a className={styles.questionLabel}>
                  Who are building Vaultka?
                </a>
                <button className={styles.questionCollapseButton} type="button">
                  -
                </button>
              </div>
              <a className={styles.answerLabel}>
                Vaultka is built by a Hong Kong based team of 11 blockchain
                engineers, product managers, TradFi traders, researchers, and
                designer, we deeply understand the community's needs with
                top-in-class execution. We perform meticulous backtesting and
                product design which aims to empower stablecoins holders to
                capitalize on their stablecoins.
              </a>
              <div className={styles.questionSeparatorLine} />
            </div>
            <div>
              <div className={styles.questionSubContainer}>
                <a className={styles.questionLabel}>
                  What will be the next step of Vaultka?
                </a>
                <button className={styles.questionCollapseButton} type="button">
                  -
                </button>
              </div>
              <a className={styles.answerLabel}>
                Team is relentlessly strategizing various protocols and offer
                the best market-neutral and risk-managed vault for the
                community. More vaults are under development stage!
              </a>
              <div className={styles.questionSeparatorLine} />
            </div>
          </div>
          <button className={styles.exploreButton} type="button">
            Explore Vaultka strategies
          </button>
        </div>
        <footer className={styles.footerContainer}>
          <div className={styles.footerTopContainer}>
            <div className={styles.footerLeftContainer}>
              <div>
                <Image
                  alt="logo"
                  height="35"
                  src="/assets/pngs/logo_with_text.png"
                  width="112"
                />
              </div>
              <a className={styles.footerLeftLabel}>
                Build up capital under Market Neutral approach
              </a>
              <div className={styles.footerLeftButtonContainer}>
                <button className={styles.socialButton} type="button">
                  <Image
                    alt="twitter"
                    height="18.31"
                    src="/assets/svgs/twitter.svg"
                    width="18.82"
                  />
                </button>
                <button className={styles.socialButton} type="button">
                  <Image
                    alt="twitter"
                    height="18.31"
                    src="/assets/svgs/twitter.svg"
                    width="18.82"
                  />
                </button>
                <button className={styles.socialButton} type="button">
                  <Image
                    alt="twitter"
                    height="18.31"
                    src="/assets/svgs/twitter.svg"
                    width="18.82"
                  />
                </button>
                <button className={styles.socialButton} type="button">
                  <Image
                    alt="twitter"
                    height="18.31"
                    src="/assets/svgs/twitter.svg"
                    width="18.82"
                  />
                </button>
              </div>
            </div>
            <div className={styles.footerRightContainer}>
              <div className={styles.footerRightButtonContainer}>
                <button className={styles.linkButton} type="button">
                  Documentation
                </button>
                <button className={styles.linkButton} type="button">
                  Github
                </button>
                <button className={styles.linkButton} type="button">
                  Vaults
                </button>
                <button className={styles.linkButton} type="button">
                  Saving
                </button>
              </div>
              <Image
                alt="Audit By"
                height="50"
                src="/assets/svgs/audit.svg"
                width="119"
              />
            </div>
          </div>
          <div className={styles.separatorLine} />
          <div className={styles.footerBottomContainer}>
            <a className={styles.rightLabel}>© 2021 All Rights Reserved</a>
            <div className={styles.policyButtonContainer}>
              <button className={styles.policyButton} type="button">
                Privacy Policy
              </button>
              <button className={styles.policyButton} type="button">
                Terms and Conditions
              </button>
            </div>
          </div>
        </footer>
      </div>
    </div>
  )
}
